mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: 1qaz@WSX3edc
  log_Level: ""
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show-line: true
  log-in-console: true
system:
  host: 0.0.0.0
  port: 8080
  env: debug
site-info:
  created_at: "2022-12-06"
  bei_an: 湘ICP备2021010654号-3
  title: FixPng个人博客
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/qq.png
  version: 6.0.2
  email: 2663456523@qq.com
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: FixPng
  job: 后端开发
  addr: 湖南长沙
  slogan: 枫枫知道
  slogan_en: FENGFENGZHIDAO
  web: http://www.fengfengzhidao.com/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao/
qq:
  app_id: ""
  key: ""
  redirect: ""
qiniu:
  enable: true
  access_key: JqOGVVUHuW5jbBtsu-x9nU6PKIcSzK3FUYXTpY0P
  secret_key: -rp-t5Kp4Pdublzp-Q8IqWqLcMJnZjwTHFSUdJZ3
  bucket: fixpng
  cdn: https://rrio8v49c.hn-bkt.clouddn.com/
  zone: z2
  prefix: "gvb"
  size: 5
email:
  host: smtp.qq.com
  port: 465
  user: 897491068@qq.com
  password: "2222"
  default-from-email: FixPng
  use_ssl: false
  user_tls: false
jwy:
  secret: ""
  expires: 0
  issuer: ""
upload:
  size: 2
  path: uploads/file/

