mysql:
  host: 127.0.0.1
  port: 3306
  db: gvb_db
  user: root
  password: 1qaz@WSX3edc
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show-line: true       # 是否显示打印行号
  log-in-console: true  # 是否显示打印路径
system:
  host: "0.0.0.0"
  port: 8080
  env: debug # debug/release/test